### ISSUE TITLE
Update Onyx+ (kiiroov21 protocol) for initial read

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-rs#158]
**Describe the bug**

tl;dr 0x1901 characteristic needs to be read on boot.

From https://metafetish.club/t/adding-new-kiiroo-onyx-plus-for-service-in-buttplug-intiface-and-buttplug-java/1035/24:

> It looks like I actually found out why it does not work. There seems to be a difference in the protocol on newer Onyx+ variants that requires some change.
> 
> I tried to implement some python code to make the motors move based on the information available for the Onyx 2 here in the forums. That did (like the Intiface Server) not work. After creating a snoop trace and inspecting it, the only difference in my code has been, that the app also ready the characteristic named “whitelist” in the configuration.
> 
> After reading from 00001901-0000-1000-8000-00805f9b34fb once, the motor actually starts moving. If this step is skipped, the device does just do nothing at all. Maybe that is also the reason why pairing it in windows might do the trick for some older versions.
> 
> I have created a paste of the code here: https://paste.ubuntu.com/p/88VsdP9h3p/ 2
> 
> What the app does for initialization (and what I just copied is):
> 
> write [0x03, 0x00, 0x64, 0x19] to 1902
> write [0x03, 0x00, 0x64, 0x00] to 1902
> read from 1901
> 
> Afterwards you can move the motor properly. Would it be possible to have the change implemented in Intiface?
> 
> Edit: It turns out that it is sufficient to read 1901 once. That seems to initialize the device.
> 
> If it is not read, there is no movement.

**Comment by udontknw** [comment]
To move my last post from the forum over to here, this is what the console gives me if my Onyx+ is detected:

```
    xSep 23 09:58:14.547  INFO buttplug::server::comm_managers::btleplug::btleplug_internal: Device Some("Onyx+") connected!
    R"P
    NSep 23 09:58:14.591  INFO btleplug::winrtble::ble::device: services Ok(3)
    Y"W
    USep 23 09:58:14.880  INFO btleplug::winrtble::ble::device: characteristics Ok(1)
    Y"W
    USep 23 09:58:15.361  INFO btleplug::winrtble::ble::device: characteristics Ok(3)
    Y"W
    USep 23 09:58:15.781  INFO btleplug::winrtble::ble::device: characteristics Ok(3)
    n"l
    jSep 23 09:58:15.781  INFO buttplug::server::comm_managers::btleplug::btleplug_internal: Device connected!
    thread 'L"J
    HSep 23 09:58:15.781  INFO buttplug::device: Found Buttplug Device Onyx+
    <unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ButtplugDeviceError(ProtocolAttributesNotFound("Cannot find identifier Onyx+ in protocol."))', S:\Intiface\buttplug-rs\buttplug\src\device\protocol\mod.rs:155:68
    stack backtrace:
       0: backtrace::backtrace::trace_unsynchronized
                 at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
       1: std::sys_common::backtrace::_print_fmt
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
       2: std::sys_common::backtrace::_print::{{impl}}::fmt
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
       3: core::fmt::write
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
       4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537
       5: std::sys_common::backtrace::_print
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
       6: std::sys_common::backtrace::print
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
       7: std::panicking::default_hook::{{closure}}
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
       8: std::panicking::default_hook
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:217
       9: std::panicking::rust_panic_with_hook
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
      10: std::panicking::begin_panic_handler
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:437
      11: core::panicking::panic_fmt
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\panicking.rs:85
      12: core::option::expect_none_failed
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\option.rs:1269
      13: core::result::Result<tuple<std::collections::hash::map::HashMap<alloc::string::String, alloc::string::String, std::collections::hash::map::RandomState>, std::collections::hash::map::HashMap<buttplug::core::messages::ButtplugDeviceMessageType, buttplug::co
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\result.rs:1005
      14: buttplug::device::protocol::ButtplugProtocolCreator::try_create<buttplug::device::protocol::kiiroo_v21::KiirooV21>
                 at S:\Intiface\buttplug-rs\buttplug\src\device\protocol\mod.rs:155
      15: buttplug::device::protocol::try_create_protocol
                 at S:\Intiface\buttplug-rs\buttplug\src\device\protocol\mod.rs:123
      16: buttplug::device::{{impl}}::try_create_device::{{closure}}
                 at S:\Intiface\buttplug-rs\buttplug\src\device\mod.rs:355
      17: core::future::from_generator::{{impl}}::poll<generator-0>
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\future\mod.rs:78
      18: buttplug::server::device_manager::wait_for_manager_events::{{closure}}::{{closure}}
                 at S:\Intiface\buttplug-rs\buttplug\src\server\device_manager.rs:113
      19: core::future::from_generator::{{impl}}::poll<generator-1>
                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\future\mod.rs:78
      20: futures_task::future_obj::{{impl}}::poll<tuple<>>
                 at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-task-0.3.5\src\future_obj.rs:86
      21: futures_task::future_obj::{{impl}}::poll<tuple<>>
                 at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-task-0.3.5\src\future_obj.rs:133
      22: futures_util::future::future::FutureExt::poll_unpin<futures_task::future_obj::FutureObj<tuple<>>>
                 at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.5\src\future\future\mod.rs:554
      23: futures_executor::thread_pool::Task::run
                 at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.5\src\thread_pool.rs:324
      24: futures_executor::thread_pool::PoolState::work
                 at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.5\src\thread_pool.rs:158
      25: futures_executor::thread_pool::{{impl}}::create::{{closure}}
                 at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.5\src\thread_pool.rs:286
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    k"i
    gSep 23 09:58:15.908  INFO buttplug::server::comm_managers::btleplug::btleplug_internal: CHANNEL CLOSED
```

So I am not yet completely sure, if there is another issue here, but at least reading the one characteristic is something required here.

**Comment by udontknw** [comment]
After digging around a bit in the code and trying to understand it, I now got it working.

It looks like it now also works without reading from 1901 (at least on Windows) after adding the changes from #162 (I hope that I am not missing a fresh rebuild somewhere). It looks like it does not work without reading 1901 on Linux.

Do we know anything about the data returned by 1901? Is there a firmware version or serial number or anything useful in there? I will try to see, if the issue reappears without the readout. I am not sure, if I might be messing things up in some way and did not start with a clean setup while testing.

**Comment by qdot** [comment]
Holy *shit* well congrats on winding your way through the codebase to identify that! I'm impressed. 👍 

@blackspherefollower You got any info on returns from the whitelist characteristic?

**Comment by qdot** [comment]
I've got a Titan 1.1 so I can possibly take a look.

**Comment by udontknw** [comment]
This is the response when reading 1901 on my Onyx+

    04 11 00 22 00 64 00 00 00 00 00 00 00 00 00 00 00 00 00 00   (20 bytes)

**Comment by udontknw** [comment]
Okay. I have now been playing around with the initialization. I think I now understand, why the app is sending some initial "junk" to the device:

If I just connect to the device without writing or reading, it disconnects automatically after just a few seconds. So I implemented some initialization and try to add the "read" call.

As soon as I do exactly what the app does (move the motor to 0x19 and back to 0x00 and then read out 1901), the Onyx+ remains connected.

So this looks as if it works kind of stable now, except for the fact that this is the first time that I look into rust code and I guess that this is not any code you would like to see in the application at all.

At least for my device, doing some initialization is kind of mandatory, otherwise it will just disconnect and reconnecting is a pain as you need to turn the device off and on again, as it looks like it refuses to talk to the same Bluetooth device afterwards again.

**Comment by qdot** [comment]
Actually we have a way to implement this in the rust code, it's just not obvious at *all* because the rust code is fairly new an undocumented.

The Lovense protocol shows what happens when a device needs to do read/writes to set up before returning itself as ready. I already have a vague version of this for the Onyx+ that I put together for someone else using your earlier read recommendation, I'll see about getting something together involving both the motor move and read, plus the config edition, and will see how that works.

**Comment by udontknw** [comment]
Yes, I have seen that.

What I did was roughly implementing the already existing read_value in BtlePlugDeviceImpl and the associated message loop and then implement the creator for the Kiiroo21 protocol and I guess that is kind of what you would be doing as well.

So I see that everything is already mostly there, but has not been required for the devices yet. But my implementation is kind of messy, so I just wait what you implement there and see, how it would be properly done. I just never got in touch with rust code before, but the structure is not a complete mess, so I think that you can get ahead of it, once you know what you are looking for, even if there is no documentation.

**Comment by udontknw** [comment]
After spending some more time to play around with the device a bit, it looks like reading is actually not necessary, but the device still requires to receive a write shortly after it has been paired.

I will create a PR for Onyx+ initialization, but someone has to double check that and maybe fix things that might have a bad style.

What it basically does is moving the motor to 0x19 and back to 0x00. This is the same that the app does and has the side effect that the user will get a nice response from the device that indicates that pairing has been successful.

The problem with this is, that it requires async_std::task and there might be a better option to get this fixed.

**Comment by qdot** [comment]
This landed, closing.

**Comment by Roboticman** [comment]
How can I put this code in the device or is there any way I make this device pair to something some how?
