### ISSUE TITLE
WeWibe 4 Plus disconnects a few seconds after connect, if client does not immediately send vibrations

### ISSUE THREAD

**Issue by udontknw** [buttplugio/buttplug-rs#187]
As already mentioned in my PR #186, the WeWibe 4 Plus does immediately lose the connection, if the device is not used right ahead.

This can be circumvented, if some vibration is sent to the device for initialization. Afterwards, it stays connected for quite some time, before the connection times out again. The connection will eventually time out, if no further commands are delivered for some time.

**Comment by qdot** [comment]
Landed @udontknw's PR for this in 0.8.4, closing.
