### ISSUE TITLE
Devices discovered whilst client is disconnected are ignored

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-rs#215]
**Describe the bug**
If a client connects to a buttplug-rs server (tested with Intiface) starts scanning, then disconnects, it's possible for devices to be connected whilst no client is connected. These devices do not get resisted in the device list: not displayed on the Intiface-desktop device list or reported t new clients that connect later.

**Expected behavior**
On disconnect, devices should stop being discovered, or if they are partway through connection, added to the device manager's device list so that the new client can use them.

**Actual behavior**
Devices connected this way are lost and need the server to be restarted. Power cycling the device is not enough, which indicated that some information about the device is being cached in the server.

**Additional context**
I'm testing with ScriptPlayer as the client (because I was testing something else first), and found that I had to restart the device scanning to trigger reconnection. This suggests that the device gets cached in the scanners seen list too. Restarting the client to restart the scanning (no stop scanning button in scriptplayer) was also not enough to get the device to be registered, although it was enough to get the device to indicate it was connected.

**Comment by qdot** [comment]
This doesn't seem to be an issue anymore. If I bring up a device on a lovense dongle, then restart the server, it will find and enumerate the device before any client connection happens. On client connection, the device will be sent as part of the initial RequestDeviceList negotiation.
