### ISSUE TITLE
ButtplugClientDevice::StopDeviceCmd() always uses index 0

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-rs#216]
**Describe the bug**
Using the C# FFI library, calling StopDeviceCmd() on a device with a non-zero index (when there is no device connected with index 0) causes an exception stating that there's no device with index 0 and the device keeps vibrating. Most likely StopDeviceCmd() is always using index 0, not the index on the device object.

**Expected behavior**
The device stops

**Actual behavior**
An exception is thrown

**Comment by qdot** [comment]
Wow, this is a bug all the way down in the core library!

https://github.com/buttplugio/buttplug-rs/blob/master/buttplug/src/client/device.rs#L585

StopDeviceCmd is formed using the default, which always sets the device index to 0. This is bad, and honestly device messages shouldn't be allowed to implement default. So I'll fix this in the trait as well as the message.
