### ISSUE TITLE
Add BLE standard battery to MagicMotion protocol

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-rs#267]
See https://github.com/buttplugio/buttplug-developer-guide/issues/17#issuecomment-768220301

Could also fix #198, but that seems like it might be a decent amount of work.

cc @stefnotch

**Comment by stefnotch** [comment]
Okay, while my magic motion lipstick does have an exposed battery service, I'm not entirely convinced that mine actually works. The only value I've gotten back so far is "100%", despite having the device turned on and connected to the PC for multiple days. 

(I tested it out with an app called [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en).)

**Comment by qdot** [comment]
Well this at least got implemented, but not sure if it's correct? Closing for at least that much, if we get more complaints about levels not lining up I'll open a new bug.
