### ISSUE TITLE
stop_all_devices() does not work as of v2.1.0

### ISSUE THREAD

**Issue by runtime-shady-backroom** [buttplugio/buttplug-rs#276]
**Describe the bug**
`ButtplugClient::stop_all_devices()` fails validation. If my understanding is correct that means that the message is being dropped.

**Expected behavior**
`ButtplugClient::stop_all_devices()` should return `Ok(()`

**Actual behavior**
`ButtplugClient::stop_all_devices()` returns:
```
 ButtplugError(ButtplugMessageError(InvalidMessageContents("Message should not have 0 for an Id. Id of 0 is reserved for system messages.")))
```

**Additional context**
This issue appears to have been introduced in a579f73ef0e44220a35933e1e465d64d464ec5b9, and first appears in version 2.1.0. version 2.0.2 is not affected. I cannot compile versions between 2.0.2 and 2.1.0, likely due to dependency issues.

**Comment by qdot** [comment]
Uh oh. I'll get that fixed ASAP, thanks for filing.
