### ISSUE TITLE
Implement XInput Device Communication Manager

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-rs#28]
**Feature Description**

Using rusty-xinput (https://github.com/Lokathor/rusty-xinput), we should be able to get a windows gamepad rumble subtype manager fairly easily.

**Comment by Shadlock0133** [comment]
I would like to try implementing this.

**Comment by qdot** [comment]
> I would like to try implementing this.

Thanks for your interest! 

Right now this is slightly out of scope for where we are with the project, as I haven't gotten the server code really started yet, and we're working on our next version of our protocol before we get started on that. 

It may be a few weeks before I can get to the point of having the pieces this would be built on top of (Our server and Device Manager/Device Configuration systems) ready to go, but once I do I'll try to let you know. :)

**Comment by Shadlock0133** [comment]
Ok, thanks.

**Comment by qdot** [comment]
Finished. Sorry for grabbing this @Shadlock0133 (Not sure if you were wanting to do it 5 months later :) ), but this would've been the worst first bug ever. Implementing it took me most of a day and required a lot of changes through multiple levels of the system, 'cause XInput is kind of its own thing. Not sure I could've even mentored this through.

**Comment by Shadlock0133** [comment]
That's fine :P
