### ISSUE TITLE
Kiiroo 2.1 vibes don't like the Onyx handshake

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-rs#281]
**Describe the bug**
The Esca 2 and Pearl 2.1 are currently disconnecting or just misbehaving due to the Onyx handshake.

The Titan 1.1 is both a vibe and makes use of the Onyx's movement commands. If it handles the onyx handshake, splitting the protocol might be the easiest/cleanest fix.

**Comment by qdot** [comment]
Just checked, Titan 1.1 works with handshake (via Buttplug Playground on buttplug-js v1.0.12 or something). Honestly, right now I'm tired enough that I'd be fine just putting in a name check for the Pearl2.1 or Esca and calling it a day. Splitting the protocol is the *right* thing to do but ehhhhhhhhhhh.

**Comment by qdot** [comment]
The Cliona also currently works, so I guess this is ONLY the Pearl2.1 and Esca?
