### ISSUE TITLE
Some PrettyLove devices are not controllable

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-rs#301]
**Describe the bug**
About half of my PrettyLove devices appear in the device list, but do nothing when sent VibrateCmd.
All PrettyLove devices use the exact same code, UUIDs, etc.
This is limited to Win10 btleplug (WebBluetooth and "Bluetooth LE Explorer" both work fine). I haven't tested on Linux or Mac.
One of the problematic devices is the Archenermy (oscillating prostate massager).

I'm logging this here, since it's device specific, but if I can narrow the bug down to a specific area of code, I may report this on btleplug too.

**Expected behavior**
The device vibrates/oscilates when sent a suitable command.

**Actual behavior**
The devices does not respond.

**Comment by Tigrejor** [comment]
Related to issue #295 
Tested Intiface and WebBluetooth on Linux and neither work.

**Comment by blackspherefollower** [comment]
Ah, yep. This is a duplicate.
