### ISSUE TITLE
Request: Support for Svakom products like Vick NEO

### ISSUE THREAD

**Issue by itsame-luigi** [buttplugio/buttplug-rs#325]
**Feature Description**

I did some digging around in the Android app and some tinkering on my own and found out how to communicate over Bluetooth LE with Svakom devices like the Vick NEO. Unfortunately, I don't know enough about Rust to figure out how to add support for it.

Svakom devices use Bluetooth LE with the following GATT service to control vibration:

**Service UUID**: `0000FFE0-0000-1000-8000-00805f9b34fb` (Simple Key Service)
**Characteristic UUID**: `0000FFE1-0000-1000-8000-00805f9b34fb` (Simple Key State)

Once connected to the device, it responds to a 6-byte message. Each message starts with a 3-byte header: `55 03 00`. The next three bytes correspond to the following values:

```
 0  1  2  3  4  5
55 03 00 ## ## ##
         \/ \/ \/
kind ----/  /  /
preset ----/  /
intensity ---/
```

- Byte 3 (i.e. `kind`) is either a value of `0x00` for general vibration, or `0x03` to use a preset sequence.
- Byte 4 (i.e. `preset`) is either `0x00` for no preset (i.e., off), or `0x01..0b` for preset vibration patterns 1-11 (see below).
- Byte 5 (i.e. `intensity`) is `0x00` for no vibration (i.e., off), or `0x01..0a`, indicating 10% increments in vibration intensity.

For general vibration (such as for app integration like is used by FeelConnect), the following sequences are used:

**General Vibration:**
- `55 03 00 00 00 00` - Vibration off
- `55 03 00 00 01 01` - Vibration intensity 10%
- ...
- `55 03 00 00 01 0a` - Vibration intensity 100%

**Presets:**
- `55 03 00 03 00 00` - Preset Vibration off
- `55 03 00 03 01 01` - Preset 1 Vibration at 10%
- ...
- `55 03 00 03 01 0a` - Preset 1 Vibration at 100%
- `55 03 00 03 02 01` - Preset 2 Vibration at 10%
- ...

I've tested these specific sequences in a windows app I threw together, and have some other experimenting to do to see what other messages it responds to. Some of my findings:

- As far as I can tell, the `kind` value only accepts either `0x00` or `0x03`.
- The device doesn't respond to presets higher than 11 (`0x0b`).
- The device doesn't respond to intensity higher than 10 (`0x0a`).

From the device manual, there are 11 presets (plus "None" for the off state), that correspond to the following values:

| Name | Decimal | Hex |
|:-|-:|-:|
| None | 0 | `0x00` |
| Surge | 1 | `0x01` |
| Tempo | 2 | `0x02` |
| Speedy | 3 | `0x03` |
| Edging | 4 | `0x04` |
| Rushing | 5 | `0x05` |
| Stamina Training | 6 | `0x06` |
| The One | 7 | `0x07` |
| The Tease | 8 | `0x08` |
| Climax | 9 | `0x09` |
| The Shock | 10 | `0x0a` |
| Seductive | 11 | `0x0b` |

As mentioned above, its possible to remotely set the intensity both for general vibration and for presets.

The Svakom devices supported by this scheme seem to be (from the BluetoothLE advertisement, unsure about case):
- `Aogu SUV`
- `Aogu SCB`
- `Ella NEO`
- `Vick NEO`
- `Emma NEO`
- `Phoenix NEO`

**Comment by qdot** [comment]
We already support the Svakom protocol and Aogu SCB. We should be able to just add the rest of these names to our config file and we'll support the rest.

**Comment by blackspherefollower** [comment]
Huh. Those first 3 bytes seem somewhat variable (I captured different numbers when work with the original Elle and the Alex NEO):
https://github.com/buttplugio/stpihkal/issues/57
https://github.com/buttplugio/stpihkal/issues/105

I'd be tempted to merge the information here into https://github.com/buttplugio/stpihkal/issues/57

**Comment by blackspherefollower** [comment]
Weird, just tested my Elle with the behaviours described here, and they're accurate, however the first 3 bytes have a definite effect: using `0x55, 0x04, 0x03` the scale changes and speeds up to 19 can be achieved (which are higher intensity than the max of 10 when using `0x55 0x03 0x00`)

**Comment by itsame-luigi** [comment]
I can also verify that the codes for the Elle seem to work with the Vick. The codes I posted came from digging around in the FeelConnect 3 app.

**Comment by qdot** [comment]
I landed this PR today and it's now shipping in Intiface Desktop, so I *think* this is closable. Lemme know if things aren't working.
