### ISSUE TITLE
Implement Lovense Protocol

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-rs#41]
**Feature Description**

Bring over protocol code from C#, maybe also implement missing packets from STPIHKAL.

If this doesn't end up implementing the battery power message (because battery isn't in the protocol yet), file as followup.

**Comment by blackspherefollower** [comment]
Is this covered by https://github.com/buttplugio/buttplug-rs/commit/a33cec84919df289b6c207881668cf15547f5469 ?

**Comment by qdot** [comment]
Yup. Very done.
