### ISSUE TITLE
Implement Spec v2 Messages

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-rs#60]
**Feature Description**

Implement new messages from Spec v2, and see how hooking them up to devices/client API works out. This isn't a final implementation, but rather a way to figure out whether the messages translate well at the API level. Spec/schema refinement may happen during this work.

- [x] RawWriteCmd
- [x] RawReadCmd
- [x] SubscribeCmd
- [x] UnsubscribeCmd
- [x] RawReading
- [x] RSSILevelCmd
- [x] RSSILevelReading
- [x] BatteryLevelCmd
- [x] BatteryLevelReading

**Comment by qdot** [comment]
Removing Shock/Pattern commands, as those are now v3.

**Comment by qdot** [comment]
Done in v0.10

**Comment by cuter44** [comment]
> 
> 
> Removing Shock/Pattern commands, as those are now v3.

Hello, would you talk about the ShockCmd?

I am working on to add Svakom Viviana protocol, which is an egg with estim feature. I have read a bit code and noticed `ShockCmd` is commented out.
I also turned to Libo Pipijing's protocol (which is known to me it featured estim). It uses a VibrateCmd to simulate. This is viable, but not zen.
So I want to know, is there any plan of ShockCmd?
