### ISSUE TITLE
ButtplugDevice::try_create_device() creates the devices before it checks it has a protocol implementation

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-rs#89]
**Describe the bug**
ButtplugDevice::try_create_device() creates the devices before it checks it has a protocol implementation.
device_mgr.get_protocol_creator() is called after device_creator.try_create_device_impl(), which connects to the device before we know if we're going to get a non-None response from get_protocol_creator().

Related, unwrap is immediately called on the response of get_protocol_creator(), which if None, causes a panic.

**Expected behavior**
No connection attempt should be made if we don't get a valid protocol creator first.

**Actual behavior**
The connection to the device is opened before a panic is thrown.

**Comment by qdot** [comment]
Landed in dev.
