### ISSUE TITLE
DeviceManager::parse_device_message() clones stateful device protocol objects

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-rs#98]
**Describe the bug**
DeviceManager::parse_device_message() takes a read lock on the device HashMap long enough to clone the device and release the lock. That means that when the device protocol impl methods are called, they're called on a clone of the device and any state is lost.

**Expected behavior**
A borrowed reference of the ButtplugDevice should be operated on.

**Actual behavior**
A clone of the ButtplugDevice is operated on.

**Additional context**
We've managed to avoid spotting this behaviour so far, but it became obvious in implementing the Kiiroo Linear logic: https://github.com/buttplugio/buttplug-rs/pull/96/commits/173edfaa034efc21b271b5a8c26c88fc6aab2143

**Comment by qdot** [comment]
This is now taken care of by a combination of two things:

- The GenericCommandManager, which handles caching of values from generic commands. This is still a work in progress, but it works ok for some protocols right now.
- The new protocol macros, which do away with most of the protocol setup boilerplate (though protocols like Lovense that have complicated initialization can still use the long form. Using these macros, it's easy to see what state is added to the base protocol struct, so it can be wrapped in synchronization types if needed.
